# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Catfish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Catfish
	pod 'Firebase/Analytics'
	pod 'FirebaseUI/Auth'
	pod 'FirebaseUI/Google'
	pod 'FirebaseUI/OAuth'

  target 'CatfishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatfishUITests' do
    # Pods for testing
  end

end

